trigger:
  branches:
    include:
      - main

pool:
  name: 'Default'  # Asegúrate de que este es el nombre correcto de tu pool

steps:
  - script: echo $(Build.SourcesDirectory)
    displayName: 'Mostrar directorio de trabajo'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true
      architecture: 'x64'
      installationPath: $(Agent.ToolsDirectory)/dotnet
      
  - script: |
      echo "Building and testing the application"
      dotnet build
      dotnet test
    displayName: 'Build and Test'    