trigger:
  branches:
    include:
      - main

pool:
  name: 'Default'  # Asegúrate de usar un agente compatible

variables:
  pythonVersion: '3.7'  # Ajusta la versión de Python si es necesario
  requirementsFile: 'requirements.txt'
  testFolder: 'test_test1.py'
  testResultsFile: 'test-results.xml'
  GH_TOKEN: $(GH_TOKEN)  # Referencia la variable secreta GH_TOKEN

steps:
  # Paso 1: Clonar repositorio de GitHub
  - task: CmdLine@2
    inputs:
      script: |
        git clone https://github.com/sammyice/python-sample-vscode-flask-tutorial.git
    displayName: 'Hacer Checkout del repositorio en GitHub'

  # Paso 2: Verificar la configuración del token GH_TOKEN
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        if (-not $env:GH_TOKEN) {
          Write-Error "El token GH_TOKEN no está configurado."
          exit 1  # Salir con un código de error
        } else {
          Write-Output "GH_TOKEN configurado correctamente."
        }
    displayName: 'Verificar la configuración del token GH_TOKEN'

  # Paso 3: Configurar Python
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(pythonVersion)'
      addToPath: true
    displayName: 'Configurar Python $(pythonVersion)'

  # Paso 4: Instalar dependencias
  - script: |
      python -m pip install --upgrade pip
      pip install -r $(requirementsFile)
    displayName: 'Instalar dependencias'

  # Paso 5: Ejecutar pruebas unitarias
  - script: |
      echo "Ejecutando pruebas unitarias en $(testFolder)"
      pytest $(testFolder) --junitxml=$(testResultsFile)
    displayName: 'Ejecutar pruebas unitarias'

  # Paso 6: Publicar resultados de pruebas
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/$(testResultsFile)'
      testResultsFormat: 'JUnit'
    displayName: 'Publicar resultados de pruebas'