trigger:
  branches:
    include:
      - main

pool:
  name: 'Default'

variables:
  pythonVersion: '3.9.6'
  requirementsFile: 'requirements.txt'
  testFolder: 'test_test1.py'
  testResultsFile: 'test-results.xml'

steps:
  - task: Checkout@1
    displayName: 'Checkout del repositorio'

