trigger:
  branches:
    include:
      - main

pool:
  name: 'Default'  # Asegúrate de que este es el nombre correcto de tu pool

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '6.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet
  - script: |
      echo "Building and testing the application"
      dotnet build
      dotnet test
    displayName: 'Build and Test'