trigger:
  branches:
    include:
      - main

pool:
  name: 'Default'  # Asegúrate de que este es el nombre correcto de tu pool

steps:
  - script: echo $(Build.SourcesDirectory)
    displayName: 'Mostrar directorio de trabajo'
  - task: UseDotNet@2
    inputs:
      packageType: '.py'
      version: '3'
      installationPath: $(Agent.ToolsDirectory)/dotnet
  - script: |
      echo "Building and testing the application"
      dotnet build
      dotnet test
    displayName: 'Build and Test'