trigger:
  branches:
    include:
      - main

pool:
  name: 'Default'

variables:
  pythonVersion: '3'  # Cambiar a una versión comúnmente disponible
  requirementsFile: 'requirements.txt'
  testFolder: 'test_test1.py'
  testResultsFile: 'test-results.xml'

steps:
  # Paso 1: Clonar repositorio de GitHub
  - task: CmdLine@2
    inputs:
      script: |
        git clone https://$(GH_TOKEN)@github.com/sammyice/python-sample-vscode-flask-tutorial.git
    displayName: 'Hacer Checkout del repositorio en GitHub'
    env:
      GH_TOKEN: $(GH_TOKEN)  # Usar la variable secreta directamente en el entorno

  # Paso 2: Configurar Python con GitHub Token
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(pythonVersion)'
      addToPath: true
    displayName: 'Configurar Python $(pythonVersion)'
    continueOnError: false

  # Paso 3: Instalar dependencias
  - script: |
      python -m pip install --upgrade pip
      pip install -r $(requirementsFile)
    displayName: 'Instalar dependencias'

  # Paso 4: Ejecutar pruebas unitarias
  - script: |
      echo "Ejecutando pruebas unitarias en $(testFolder)"
      pytest $(testFolder) --junitxml=$(testResultsFile)
    displayName: 'Ejecutar pruebas unitarias'

  # Paso 5: Publicar resultados de pruebas
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/$(testResultsFile)'
      testResultsFormat: 'JUnit'
    displayName: 'Publicar resultados de pruebas'